import { useState } from "react";
import InfoBanner from "../../elements/InfoBanner";
import HeaderBanner from "../../elements/HeaderBanner";
import PolicyTargetModal from "../../components/PolicyTargetModal";
import { ChevronDown } from "lucide-react";
import EuSkillsContent from "./policytab/EuSkillsContent";
import DigitalDecadeContent from "./policytab/DigitalDecadeContent";
import RecoveryPlanContent from "./policytab/RecoveryPlanContent";
import CyprusStrategyContent from "./policytab/CyprusStrategyContent";
import Tabs from "../../elements/Tabs";
import FactBanner from "../../elements/FactBanner";


export default function PolicyMonitoring() {
    const [isPolicyTargetModalOpen, setIsPolicyTargetModalOpen] = useState(false);

    const [activeTab, setActiveTab] = useState("eu-skills");

    const tabs = [
        {
            id: "eu-skills",
            label: "EU Skills Agenda 2030",
        },
        {
            id: "eu-digital",
            label: "EU Digital Decade",
        },
        {
            id: "national-recovery",
            label: "National Recovery Plan",
        },
        {
            id: "cyprus-strategy",
            label: "Cyprus 2035 Strategy",
        },
    ];

    return (
        <>


            <div className="flex flex-col w-full gap-2">
                <HeaderBanner
                    breadcrumb="Policy Monitoring"
                    title="Policy Monitoring"
                    description="EU commitments · national targets · compliance tracking · deadline management"
                    buttons={[
                        {
                            text: "Framework: All",
                            icon: ChevronDown,
                            variant: "white",
                            onClick: () => console.log("Year clicked"),
                        },
                        {
                            text: "Add Policy Target",
                            icon: ChevronDown,
                            variant: "blue",
                            onClick: () => setIsPolicyTargetModalOpen(true),
                        },
                    ]}
                />
                <InfoBanner notif="These indicators are benchmark and contextual data — not AI Engine outputs."
                    info="All EU and national indicators displayed on this page are sourced from Eurostat, CEDEFOP, and CYSTAT, and are not calculated by the platform’s AI Engine. Data can only be classified as platform-generated output if it is derived directly from the CYGraduates dataset or from sources validated by the team. The “Source” column indicates the origin of each figure." />
                <FactBanner info="Before using these indicators for official reporting, ensure that each figure includes its source, calculation methodology, and review status. Policy alerts generated by the platform should not be used directly without validation from the team." />


                <Tabs
                    tabs={tabs}
                    value={activeTab}
                    onChange={setActiveTab}
                />

                {activeTab === "eu-skills" && (
                    <EuSkillsContent />
                )}

                {activeTab === "eu-digital" && (
                    <DigitalDecadeContent />
                )}

                {activeTab === "national-recovery" && (
                    <RecoveryPlanContent />
                )}

                {activeTab === "cyprus-strategy" && (
                    <CyprusStrategyContent />
                )}



                <PolicyTargetModal
                    isOpen={isPolicyTargetModalOpen}
                    onClose={() => setIsPolicyTargetModalOpen(false)}
                />
            </div>

        </>
    );
}
